<?php

return [
    'starting_love_seeds' => 120,

    'ambience' => [
        'vibe_thresholds' => [
            'bright' => 70,
            'calm' => 40,
            'quiet' => 0,
        ],
    ],

    'world_types' => [
        'garden' => [
            'label' => 'Enchanted Garden',
            'layers' => ['sky', 'ground', 'foreground'],
        ],
        'house' => [
            'label' => 'Cozy Cottage',
            'layers' => ['sky', 'ground', 'foreground'],
        ],
        'kitchen' => [
            'label' => 'Cute Kitchen',
            'layers' => ['sky', 'ground', 'foreground'],
        ],
        'beach' => [
            'label' => 'Beach Hut',
            'layers' => ['sky', 'ground', 'foreground'],
        ],
        'space' => [
            'label' => 'Space Station',
            'layers' => ['sky', 'ground', 'foreground'],
        ],
        'mountain' => [
            'label' => 'Mountain Cabin',
            'layers' => ['sky', 'ground', 'foreground'],
        ],
    ],

    'catalog' => [
        'garden_heart_tree' => [
            'name' => 'Heart Tree',
            'category' => 'structure',
            'rarity' => 'common',
            'world_types' => ['garden'],
            'max_level' => 3,
            'costs' => [
                1 => ['love_seeds' => 0],
                2 => ['love_seeds' => 25],
                3 => ['love_seeds' => 40],
            ],
            'unlocks' => ['world_level' => 1],
            'visuals' => [1 => 'sapling', 2 => 'blossom', 3 => 'radiant'],
            'starter' => true,
            'default_slot' => 'core',
        ],
        'garden_lantern_path' => [
            'name' => 'Lantern Path',
            'category' => 'decor',
            'rarity' => 'common',
            'world_types' => ['garden'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 20], 2 => ['love_seeds' => 35]],
            'unlocks' => ['world_level' => 1],
            'visuals' => [1 => 'lanterns', 2 => 'glow_trail'],
        ],
        'garden_koi_pond' => [
            'name' => 'Koi Pond',
            'category' => 'utility',
            'rarity' => 'rare',
            'world_types' => ['garden'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 30], 2 => ['love_seeds' => 45]],
            'unlocks' => ['world_level' => 2],
            'visuals' => [1 => 'still_water', 2 => 'sparkling_water'],
        ],
        'garden_butterfly_haven' => [
            'name' => 'Butterfly Haven',
            'category' => 'pet',
            'rarity' => 'rare',
            'world_types' => ['garden'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 25], 2 => ['love_seeds' => 35]],
            'unlocks' => ['world_level' => 2],
            'visuals' => [1 => 'few_butterflies', 2 => 'butterfly_swarm'],
        ],
        'garden_sun_dial' => [
            'name' => 'Sun Dial',
            'category' => 'decor',
            'rarity' => 'epic',
            'world_types' => ['garden'],
            'max_level' => 1,
            'costs' => [1 => ['love_seeds' => 30]],
            'unlocks' => ['world_level' => 1, 'mission_completions' => 1],
            'visuals' => [1 => 'polished_stone'],
        ],
        'garden_picnic_set' => [
            'name' => 'Picnic Set',
            'category' => 'utility',
            'rarity' => 'common',
            'world_types' => ['garden'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 18], 2 => ['love_seeds' => 28]],
            'unlocks' => ['world_level' => 1],
            'visuals' => [1 => 'blanket', 2 => 'full_spread'],
        ],
        'garden_wishing_well' => [
            'name' => 'Wishing Well',
            'category' => 'structure',
            'rarity' => 'rare',
            'world_types' => ['garden'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 26], 2 => ['love_seeds' => 44]],
            'unlocks' => ['world_level' => 3],
            'visuals' => [1 => 'simple_well', 2 => 'engraved_well'],
        ],
        'garden_flower_arch' => [
            'name' => 'Flower Arch',
            'category' => 'decor',
            'rarity' => 'common',
            'world_types' => ['garden'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 16], 2 => ['love_seeds' => 26]],
            'unlocks' => ['world_level' => 2],
            'visuals' => [1 => 'buds', 2 => 'full_bloom'],
        ],

        'house_cottage_core' => [
            'name' => 'Cottage Core',
            'category' => 'structure',
            'rarity' => 'common',
            'world_types' => ['house'],
            'max_level' => 3,
            'costs' => [1 => ['love_seeds' => 0], 2 => ['love_seeds' => 30], 3 => ['love_seeds' => 50]],
            'unlocks' => ['world_level' => 1],
            'visuals' => [1 => 'cottage_small', 2 => 'cottage_warm', 3 => 'cottage_grand'],
            'starter' => true,
            'default_slot' => 'core',
        ],
        'house_front_porch' => [
            'name' => 'Front Porch',
            'category' => 'decor',
            'rarity' => 'common',
            'world_types' => ['house'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 22], 2 => ['love_seeds' => 32]],
            'unlocks' => ['world_level' => 1],
            'visuals' => [1 => 'basic_porch', 2 => 'flower_porch'],
        ],
        'house_window_box' => [
            'name' => 'Window Box',
            'category' => 'decor',
            'rarity' => 'common',
            'world_types' => ['house'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 15], 2 => ['love_seeds' => 24]],
            'unlocks' => ['world_level' => 1],
            'visuals' => [1 => 'small_box', 2 => 'flowered_box'],
        ],
        'house_fireplace' => [
            'name' => 'Fireplace',
            'category' => 'utility',
            'rarity' => 'rare',
            'world_types' => ['house'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 28], 2 => ['love_seeds' => 42]],
            'unlocks' => ['world_level' => 2],
            'visuals' => [1 => 'gentle_fire', 2 => 'warm_fire'],
        ],
        'house_reading_nook' => [
            'name' => 'Reading Nook',
            'category' => 'utility',
            'rarity' => 'common',
            'world_types' => ['house'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 20], 2 => ['love_seeds' => 30]],
            'unlocks' => ['world_level' => 2],
            'visuals' => [1 => 'single_chair', 2 => 'dual_chair'],
        ],
        'house_pet_bed' => [
            'name' => 'Pet Bed',
            'category' => 'pet',
            'rarity' => 'rare',
            'world_types' => ['house'],
            'max_level' => 1,
            'costs' => [1 => ['love_seeds' => 24]],
            'unlocks' => ['world_level' => 2],
            'visuals' => [1 => 'cozy_bed'],
        ],
        'house_wind_chime' => [
            'name' => 'Wind Chime',
            'category' => 'decor',
            'rarity' => 'common',
            'world_types' => ['house'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 14], 2 => ['love_seeds' => 22]],
            'unlocks' => ['world_level' => 1],
            'visuals' => [1 => 'light_chime', 2 => 'silver_chime'],
        ],
        'house_memory_frame' => [
            'name' => 'Memory Frame',
            'category' => 'utility',
            'rarity' => 'epic',
            'world_types' => ['house'],
            'max_level' => 1,
            'costs' => [1 => ['love_seeds' => 40]],
            'unlocks' => ['world_level' => 3, 'mission_completions' => 2],
            'visuals' => [1 => 'gold_frame'],
        ],

        'kitchen_hearth' => [
            'name' => 'Kitchen Hearth',
            'category' => 'structure',
            'rarity' => 'common',
            'world_types' => ['kitchen'],
            'max_level' => 3,
            'costs' => [1 => ['love_seeds' => 0], 2 => ['love_seeds' => 28], 3 => ['love_seeds' => 46]],
            'unlocks' => ['world_level' => 1],
            'visuals' => [1 => 'starter_hearth', 2 => 'chef_hearth', 3 => 'festival_hearth'],
            'starter' => true,
            'default_slot' => 'core',
        ],
        'kitchen_spice_rack' => [
            'name' => 'Spice Rack',
            'category' => 'decor',
            'rarity' => 'common',
            'world_types' => ['kitchen'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 18], 2 => ['love_seeds' => 28]],
            'unlocks' => ['world_level' => 1],
            'visuals' => [1 => 'small_rack', 2 => 'full_rack'],
        ],
        'kitchen_tea_station' => [
            'name' => 'Tea Station',
            'category' => 'utility',
            'rarity' => 'rare',
            'world_types' => ['kitchen'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 22], 2 => ['love_seeds' => 34]],
            'unlocks' => ['world_level' => 2],
            'visuals' => [1 => 'basic_station', 2 => 'ceramic_station'],
        ],
        'kitchen_cookie_jar' => [
            'name' => 'Cookie Jar',
            'category' => 'decor',
            'rarity' => 'common',
            'world_types' => ['kitchen'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 16], 2 => ['love_seeds' => 22]],
            'unlocks' => ['world_level' => 1],
            'visuals' => [1 => 'plain_jar', 2 => 'patterned_jar'],
        ],
        'kitchen_breakfast_nook' => [
            'name' => 'Breakfast Nook',
            'category' => 'utility',
            'rarity' => 'rare',
            'world_types' => ['kitchen'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 24], 2 => ['love_seeds' => 38]],
            'unlocks' => ['world_level' => 2],
            'visuals' => [1 => 'two_chairs', 2 => 'window_nook'],
        ],
        'kitchen_recipe_board' => [
            'name' => 'Recipe Board',
            'category' => 'decor',
            'rarity' => 'common',
            'world_types' => ['kitchen'],
            'max_level' => 1,
            'costs' => [1 => ['love_seeds' => 20]],
            'unlocks' => ['world_level' => 1],
            'visuals' => [1 => 'chalk_board'],
        ],
        'kitchen_cat_stool' => [
            'name' => 'Cat Stool',
            'category' => 'pet',
            'rarity' => 'rare',
            'world_types' => ['kitchen'],
            'max_level' => 1,
            'costs' => [1 => ['love_seeds' => 26]],
            'unlocks' => ['world_level' => 2],
            'visuals' => [1 => 'cat_stool'],
        ],
        'kitchen_window_herbs' => [
            'name' => 'Window Herbs',
            'category' => 'decor',
            'rarity' => 'common',
            'world_types' => ['kitchen'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 14], 2 => ['love_seeds' => 22]],
            'unlocks' => ['world_level' => 1],
            'visuals' => [1 => 'small_herbs', 2 => 'lush_herbs'],
        ],

        'beach_hut_core' => [
            'name' => 'Beach Hut',
            'category' => 'structure',
            'rarity' => 'common',
            'world_types' => ['beach'],
            'max_level' => 3,
            'costs' => [1 => ['love_seeds' => 0], 2 => ['love_seeds' => 32], 3 => ['love_seeds' => 52]],
            'unlocks' => ['world_level' => 1],
            'visuals' => [1 => 'wood_hut', 2 => 'painted_hut', 3 => 'resort_hut'],
            'starter' => true,
            'default_slot' => 'core',
        ],
        'beach_hammock' => [
            'name' => 'Hammock',
            'category' => 'decor',
            'rarity' => 'common',
            'world_types' => ['beach'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 20], 2 => ['love_seeds' => 30]],
            'unlocks' => ['world_level' => 1],
            'visuals' => [1 => 'single_hammock', 2 => 'double_hammock'],
        ],
        'beach_tiki_torch' => [
            'name' => 'Tiki Torch',
            'category' => 'decor',
            'rarity' => 'common',
            'world_types' => ['beach'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 16], 2 => ['love_seeds' => 24]],
            'unlocks' => ['world_level' => 1],
            'visuals' => [1 => 'small_torch', 2 => 'twin_torch'],
        ],
        'beach_surf_rack' => [
            'name' => 'Surf Rack',
            'category' => 'utility',
            'rarity' => 'rare',
            'world_types' => ['beach'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 24], 2 => ['love_seeds' => 36]],
            'unlocks' => ['world_level' => 2],
            'visuals' => [1 => 'two_boards', 2 => 'full_rack'],
        ],
        'beach_shell_path' => [
            'name' => 'Shell Path',
            'category' => 'decor',
            'rarity' => 'common',
            'world_types' => ['beach'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 14], 2 => ['love_seeds' => 20]],
            'unlocks' => ['world_level' => 1],
            'visuals' => [1 => 'shells', 2 => 'spiral_shells'],
        ],
        'beach_fire_pit' => [
            'name' => 'Fire Pit',
            'category' => 'utility',
            'rarity' => 'rare',
            'world_types' => ['beach'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 28], 2 => ['love_seeds' => 40]],
            'unlocks' => ['world_level' => 2],
            'visuals' => [1 => 'embers', 2 => 'campfire'],
        ],
        'beach_parrot_perch' => [
            'name' => 'Parrot Perch',
            'category' => 'pet',
            'rarity' => 'rare',
            'world_types' => ['beach'],
            'max_level' => 1,
            'costs' => [1 => ['love_seeds' => 30]],
            'unlocks' => ['world_level' => 2],
            'visuals' => [1 => 'color_parrot'],
        ],
        'beach_memory_frame' => [
            'name' => 'Memory Frame',
            'category' => 'utility',
            'rarity' => 'epic',
            'world_types' => ['beach'],
            'max_level' => 1,
            'costs' => [1 => ['love_seeds' => 42]],
            'unlocks' => ['world_level' => 3, 'mission_completions' => 2],
            'visuals' => [1 => 'coral_frame'],
        ],

        'space_hab_core' => [
            'name' => 'Habitat Core',
            'category' => 'structure',
            'rarity' => 'common',
            'world_types' => ['space'],
            'max_level' => 3,
            'costs' => [1 => ['love_seeds' => 0], 2 => ['love_seeds' => 34], 3 => ['love_seeds' => 56]],
            'unlocks' => ['world_level' => 1],
            'visuals' => [1 => 'starter_hab', 2 => 'orbital_hab', 3 => 'stellar_hab'],
            'starter' => true,
            'default_slot' => 'core',
        ],
        'space_star_window' => [
            'name' => 'Star Window',
            'category' => 'decor',
            'rarity' => 'common',
            'world_types' => ['space'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 18], 2 => ['love_seeds' => 26]],
            'unlocks' => ['world_level' => 1],
            'visuals' => [1 => 'single_window', 2 => 'panoramic_window'],
        ],
        'space_holo_garden' => [
            'name' => 'Holo Garden',
            'category' => 'utility',
            'rarity' => 'rare',
            'world_types' => ['space'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 26], 2 => ['love_seeds' => 40]],
            'unlocks' => ['world_level' => 2],
            'visuals' => [1 => 'small_holo', 2 => 'lush_holo'],
        ],
        'space_satellite_dish' => [
            'name' => 'Satellite Dish',
            'category' => 'utility',
            'rarity' => 'rare',
            'world_types' => ['space'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 24], 2 => ['love_seeds' => 36]],
            'unlocks' => ['world_level' => 2],
            'visuals' => [1 => 'basic_dish', 2 => 'quantum_dish'],
        ],
        'space_robot_pet' => [
            'name' => 'Robot Pet',
            'category' => 'pet',
            'rarity' => 'epic',
            'world_types' => ['space'],
            'max_level' => 1,
            'costs' => [1 => ['love_seeds' => 34]],
            'unlocks' => ['world_level' => 2, 'mission_completions' => 1],
            'visuals' => [1 => 'helper_bot'],
        ],
        'space_nebula_projector' => [
            'name' => 'Nebula Projector',
            'category' => 'decor',
            'rarity' => 'common',
            'world_types' => ['space'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 20], 2 => ['love_seeds' => 30]],
            'unlocks' => ['world_level' => 1],
            'visuals' => [1 => 'small_projection', 2 => 'wide_projection'],
        ],
        'space_comms_panel' => [
            'name' => 'Comms Panel',
            'category' => 'utility',
            'rarity' => 'common',
            'world_types' => ['space'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 18], 2 => ['love_seeds' => 28]],
            'unlocks' => ['world_level' => 1],
            'visuals' => [1 => 'standard_panel', 2 => 'advanced_panel'],
        ],
        'space_memory_frame' => [
            'name' => 'Memory Frame',
            'category' => 'utility',
            'rarity' => 'epic',
            'world_types' => ['space'],
            'max_level' => 1,
            'costs' => [1 => ['love_seeds' => 44]],
            'unlocks' => ['world_level' => 3, 'mission_completions' => 2],
            'visuals' => [1 => 'holo_frame'],
        ],

        'mountain_lodge_core' => [
            'name' => 'Lodge Core',
            'category' => 'structure',
            'rarity' => 'common',
            'world_types' => ['mountain'],
            'max_level' => 3,
            'costs' => [1 => ['love_seeds' => 0], 2 => ['love_seeds' => 30], 3 => ['love_seeds' => 48]],
            'unlocks' => ['world_level' => 1],
            'visuals' => [1 => 'small_lodge', 2 => 'warm_lodge', 3 => 'winter_lodge'],
            'starter' => true,
            'default_slot' => 'core',
        ],
        'mountain_fireplace' => [
            'name' => 'Stone Fireplace',
            'category' => 'utility',
            'rarity' => 'rare',
            'world_types' => ['mountain'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 26], 2 => ['love_seeds' => 38]],
            'unlocks' => ['world_level' => 2],
            'visuals' => [1 => 'embers', 2 => 'steady_fire'],
        ],
        'mountain_pine_arch' => [
            'name' => 'Pine Arch',
            'category' => 'decor',
            'rarity' => 'common',
            'world_types' => ['mountain'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 16], 2 => ['love_seeds' => 24]],
            'unlocks' => ['world_level' => 1],
            'visuals' => [1 => 'pine_small', 2 => 'pine_full'],
        ],
        'mountain_hot_cocoa_bar' => [
            'name' => 'Hot Cocoa Bar',
            'category' => 'utility',
            'rarity' => 'common',
            'world_types' => ['mountain'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 20], 2 => ['love_seeds' => 30]],
            'unlocks' => ['world_level' => 1],
            'visuals' => [1 => 'small_bar', 2 => 'festival_bar'],
        ],
        'mountain_wolf_statue' => [
            'name' => 'Wolf Statue',
            'category' => 'decor',
            'rarity' => 'rare',
            'world_types' => ['mountain'],
            'max_level' => 1,
            'costs' => [1 => ['love_seeds' => 28]],
            'unlocks' => ['world_level' => 2],
            'visuals' => [1 => 'carved_wolf'],
        ],
        'mountain_snow_lantern' => [
            'name' => 'Snow Lantern',
            'category' => 'decor',
            'rarity' => 'common',
            'world_types' => ['mountain'],
            'max_level' => 2,
            'costs' => [1 => ['love_seeds' => 14], 2 => ['love_seeds' => 22]],
            'unlocks' => ['world_level' => 1],
            'visuals' => [1 => 'small_light', 2 => 'warm_light'],
        ],
        'mountain_fox_pet' => [
            'name' => 'Fox Pet',
            'category' => 'pet',
            'rarity' => 'rare',
            'world_types' => ['mountain'],
            'max_level' => 1,
            'costs' => [1 => ['love_seeds' => 30]],
            'unlocks' => ['world_level' => 2, 'mission_completions' => 1],
            'visuals' => [1 => 'snow_fox'],
        ],
        'mountain_memory_frame' => [
            'name' => 'Memory Frame',
            'category' => 'utility',
            'rarity' => 'epic',
            'world_types' => ['mountain'],
            'max_level' => 1,
            'costs' => [1 => ['love_seeds' => 42]],
            'unlocks' => ['world_level' => 3, 'mission_completions' => 2],
            'visuals' => [1 => 'wood_frame'],
        ],
    ],
];
