<?php

return [
    'starting_love_seeds' => 120,

    'vibe' => [
        'recent_days' => 7,
        'xp_target_per_window' => 140,
        'weights' => [
            'mood' => 0.5,
            'xp_rate' => 0.35,
            'repair' => 0.15,
        ],
        'repair_bonus_per_completion' => 40,
        'thresholds' => [
            'bright' => 68,
            'calm' => 42,
        ],
    ],

    'world_types' => [
        'garden' => [
            'label' => 'Enchanted Garden',
            'scene_layers' => [
                'sky_day' => 'resources/assets/worldv2/garden/scene/bg_sky_day.png',
                'sky_night' => 'resources/assets/worldv2/garden/scene/bg_sky_night.png',
                'mid' => 'resources/assets/worldv2/garden/scene/mid_trees.png',
                'ground' => 'resources/assets/worldv2/garden/scene/ground_grass.png',
                'path' => 'resources/assets/worldv2/garden/scene/path_tiles.png',
            ],
            'slots' => ['s01', 's02', 's03', 's04', 's05', 's06', 's07', 's08', 's09', 's10', 's11', 's12'],
        ],
        'cottage' => [
            'label' => 'Cozy Cottage',
            'scene_layers' => [
                'sky' => 'resources/assets/worldv2/cottage/scene/bg_sky_sunset.png',
                'mid' => 'resources/assets/worldv2/cottage/scene/mid_hills.png',
                'ground' => 'resources/assets/worldv2/cottage/scene/ground_cobble.png',
            ],
            'slots' => ['s01', 's02', 's03', 's04', 's05', 's06', 's07', 's08', 's09', 's10', 's11', 's12'],
        ],
        'kitchen' => [
            'label' => 'Cute Kitchen',
            'scene_layers' => [
                'wall' => 'resources/assets/worldv2/kitchen/scene/bg_wall.png',
                'counter' => 'resources/assets/worldv2/kitchen/scene/counter.png',
                'shelf' => 'resources/assets/worldv2/kitchen/scene/shelf.png',
            ],
            'slots' => ['s01', 's02', 's03', 's04', 's05', 's06', 's07', 's08', 's09'],
        ],
    ],

    'catalog' => [
        'garden_core_gazebo' => [
            'name' => 'Gazebo',
            'category' => 'core',
            'world_types' => ['garden'],
            'starter' => true,
            'default_slot' => 's06',
            'max_level' => 3,
            'costs' => [1 => ['love_seeds' => 0], 2 => ['love_seeds' => 30], 3 => ['love_seeds' => 50]],
            'unlocks' => ['world_level' => 1],
            'sprites' => [
                1 => 'resources/assets/worldv2/garden/items/core_gazebo_lv1.png',
                2 => 'resources/assets/worldv2/garden/items/core_gazebo_lv2.png',
                3 => 'resources/assets/worldv2/garden/items/core_gazebo_lv3.png',
            ],
        ],
        'garden_decor_flowerbed' => [
            'name' => 'Flower Bed',
            'category' => 'decor',
            'world_types' => ['garden'],
            'max_level' => 3,
            'costs' => [1 => ['love_seeds' => 18], 2 => ['love_seeds' => 28], 3 => ['love_seeds' => 40]],
            'unlocks' => ['world_level' => 1],
            'sprites' => [
                1 => 'resources/assets/worldv2/garden/items/decor_flowerbed_lv1.png',
                2 => 'resources/assets/worldv2/garden/items/decor_flowerbed_lv2.png',
                3 => 'resources/assets/worldv2/garden/items/decor_flowerbed_lv3.png',
            ],
        ],
        'garden_decor_fountain' => [
            'name' => 'Fountain',
            'category' => 'utility',
            'world_types' => ['garden'],
            'max_level' => 1,
            'costs' => [1 => ['love_seeds' => 26]],
            'unlocks' => ['world_level' => 2],
            'sprites' => [1 => 'resources/assets/worldv2/garden/items/decor_fountain_lv1.png'],
        ],
        'garden_decor_lantern' => [
            'name' => 'Lanterns',
            'category' => 'comfort',
            'world_types' => ['garden'],
            'max_level' => 1,
            'costs' => [1 => ['love_seeds' => 14]],
            'unlocks' => ['world_level' => 1],
            'sprites' => [1 => 'resources/assets/worldv2/garden/items/decor_lantern_lv1.png'],
        ],
        'garden_decor_arch' => [
            'name' => 'Flower Arch',
            'category' => 'decor',
            'world_types' => ['garden'],
            'max_level' => 1,
            'costs' => [1 => ['love_seeds' => 20]],
            'unlocks' => ['world_level' => 2],
            'sprites' => [1 => 'resources/assets/worldv2/garden/items/decor_arch_lv1.png'],
        ],

        'cottage_core_cottage' => [
            'name' => 'Cottage Home',
            'category' => 'core',
            'world_types' => ['cottage'],
            'starter' => true,
            'default_slot' => 's06',
            'max_level' => 3,
            'costs' => [1 => ['love_seeds' => 0], 2 => ['love_seeds' => 32], 3 => ['love_seeds' => 52]],
            'unlocks' => ['world_level' => 1],
            'sprites' => [
                1 => 'resources/assets/worldv2/cottage/items/core_cottage_lv1.png',
                2 => 'resources/assets/worldv2/cottage/items/core_cottage_lv2.png',
                3 => 'resources/assets/worldv2/cottage/items/core_cottage_lv3.png',
            ],
        ],
        'cottage_decor_fence' => [
            'name' => 'Fence',
            'category' => 'decor',
            'world_types' => ['cottage'],
            'max_level' => 1,
            'costs' => [1 => ['love_seeds' => 20]],
            'unlocks' => ['world_level' => 1],
            'sprites' => [1 => 'resources/assets/worldv2/cottage/items/decor_fence_lv1.png'],
        ],
        'cottage_decor_mailbox' => [
            'name' => 'Mailbox',
            'category' => 'utility',
            'world_types' => ['cottage'],
            'max_level' => 1,
            'costs' => [1 => ['love_seeds' => 16]],
            'unlocks' => ['world_level' => 1],
            'sprites' => [1 => 'resources/assets/worldv2/cottage/items/decor_mailbox_lv1.png'],
        ],
        'cottage_decor_teatable' => [
            'name' => 'Tea Table',
            'category' => 'comfort',
            'world_types' => ['cottage'],
            'max_level' => 1,
            'costs' => [1 => ['love_seeds' => 24]],
            'unlocks' => ['world_level' => 2],
            'sprites' => [1 => 'resources/assets/worldv2/cottage/items/decor_teatable_lv1.png'],
        ],
        'cottage_decor_windowvines' => [
            'name' => 'Window Vines',
            'category' => 'decor',
            'world_types' => ['cottage'],
            'max_level' => 1,
            'costs' => [1 => ['love_seeds' => 14]],
            'unlocks' => ['world_level' => 1],
            'sprites' => [1 => 'resources/assets/worldv2/cottage/items/decor_windowvines_lv1.png'],
        ],

        'kitchen_core_counter' => [
            'name' => 'Kitchen Station',
            'category' => 'core',
            'world_types' => ['kitchen'],
            'starter' => true,
            'default_slot' => 's05',
            'max_level' => 3,
            'costs' => [1 => ['love_seeds' => 0], 2 => ['love_seeds' => 30], 3 => ['love_seeds' => 48]],
            'unlocks' => ['world_level' => 1],
            'sprites' => [
                1 => 'resources/assets/worldv2/kitchen/items/core_counter_lv1.png',
                2 => 'resources/assets/worldv2/kitchen/items/core_counter_lv2.png',
                3 => 'resources/assets/worldv2/kitchen/items/core_counter_lv3.png',
            ],
        ],
        'kitchen_decor_coffee' => [
            'name' => 'Coffee Machine',
            'category' => 'utility',
            'world_types' => ['kitchen'],
            'max_level' => 1,
            'costs' => [1 => ['love_seeds' => 18]],
            'unlocks' => ['world_level' => 1],
            'sprites' => [1 => 'resources/assets/worldv2/kitchen/items/decor_coffee_lv1.png'],
        ],
        'kitchen_decor_dishrack' => [
            'name' => 'Dish Rack',
            'category' => 'utility',
            'world_types' => ['kitchen'],
            'max_level' => 1,
            'costs' => [1 => ['love_seeds' => 16]],
            'unlocks' => ['world_level' => 1],
            'sprites' => [1 => 'resources/assets/worldv2/kitchen/items/decor_dishrack_lv1.png'],
        ],
        'kitchen_decor_spicejars' => [
            'name' => 'Spice Jars',
            'category' => 'decor',
            'world_types' => ['kitchen'],
            'max_level' => 1,
            'costs' => [1 => ['love_seeds' => 14]],
            'unlocks' => ['world_level' => 1],
            'sprites' => [1 => 'resources/assets/worldv2/kitchen/items/decor_spicejars_lv1.png'],
        ],
        'kitchen_decor_plant' => [
            'name' => 'Shelf Plant',
            'category' => 'comfort',
            'world_types' => ['kitchen'],
            'max_level' => 1,
            'costs' => [1 => ['love_seeds' => 14]],
            'unlocks' => ['world_level' => 1],
            'sprites' => [1 => 'resources/assets/worldv2/kitchen/items/decor_plant_lv1.png'],
        ],
    ],
];
